[INFR] Fix workflows, Added Validator and VeraPDF

diff --git a/.github/workflows/build.release.yml b/.github/workflows/build.release.yml
--- a/.github/workflows/build.release.yml
+++ b/.github/workflows/build.release.yml
@@ -44,6 +44,12 @@ jobs:
           extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, bcmath, intl, gd, exif, iconv, imagick, json, xdebug
           coverage: xdebug
 
+      - name: Set up JDK 11
+        uses: actions/setup-java@v5
+        with:
+          java-version: "11"
+          distribution: "temurin"
+
       - name: Get Composer Cache Directory
         id: composer-cache
         run: |
@@ -97,6 +103,93 @@ jobs:
           vendor/bin/phpunit --stop-on-failure --configuration build/phpunit.xml
         env:
           XDEBUG_MODE: coverage
+
+      - name: Cache Key (Schematron)
+        id: hash-validator
+        run: |
+          echo "hash=$(echo '${{ env.VALIDATORURL }} ${{ env.VALIDATORSCENARIOURL }}' | sha256sum | cut -c1-16)" >> $GITHUB_OUTPUT
+
+      - name: Cache Application (Schematron)
+        id: cache-validator
+        uses: actions/cache@v4
+        with:
+          path: ${{ env.VALIDATORPATH }}
+          key: ${{ runner.os }}-8.4-validator-${{ steps.hash-validator.outputs.hash }}
+
+      - name: Download Application (Schematron)
+        if: steps.cache-validator.outputs.cache-hit != 'true'
+        run: |
+          rm -rf $VALIDATORPATH
+          mkdir -p $VALIDATORPATH
+          wget $VALIDATORURL -O $VALIDATORPATH/$VALIDATORZIPFILENAME
+          wget $VALIDATORSCENARIOURL -O $VALIDATORPATH/$VALIDATORSCENARIOZIPFILENAME
+          unzip $VALIDATORPATH/$VALIDATORZIPFILENAME -d $VALIDATORPATH
+          unzip $VALIDATORPATH/$VALIDATORSCENARIOZIPFILENAME -d $VALIDATORPATH
+
+      - name: Run Tests (Schematron)
+        run: |
+          set -e
+          java -jar $VALIDATORPATH/$VALIDATORJARFILENAME -r $VALIDATORPATH -s $VALIDATORPATH/$VALIDATORSCENARIOFILENAME tests/assets/00_case_comfort_simple.xml
+          java -jar $VALIDATORPATH/$VALIDATORJARFILENAME -r $VALIDATORPATH -s $VALIDATORPATH/$VALIDATORSCENARIOFILENAME tests/assets/00_case_comfort_simple_dto.xml
+
+      - name: Cache Key (VeraPDF)
+        id: hash-verapdf
+        run: |
+          echo "hash=$(echo '${{ env.VERAPDFURL }}' | sha256sum | cut -c1-16)" >> $GITHUB_OUTPUT
+
+      - name: Cache Application (VeraPDF)
+        id: cache-verapdf
+        uses: actions/cache@v4
+        with:
+          path: ${{ env.VERAPDFPATH }}
+          key: ${{ runner.os }}-8.4-verapdf-${{ steps.hash-verapdf.outputs.hash }}
+
+      - name: Download Application (VeraPDF)
+        if: steps.cache-verapdf.outputs.cache-hit != 'true'
+        run: |
+          rm -rf $VERAPDFPATH
+          mkdir -p $VERAPDFPATH
+          wget $VERAPDFURL -O $VERAPDFPATH/$VERAPDFZIPFILENAME
+          unzip -j $VERAPDFPATH/$VERAPDFZIPFILENAME -d $VERAPDFPATH
+          rm -f $VERAPDFPATH/$VERAPDFZIPFILENAME
+
+      - name: Run Tests (VeraPDF)
+        continue-on-error: true
+        run: |
+          set -e
+          echo "Creating veraPDF install config"
+          echo "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?>
+            <AutomatedInstallation langpack=\"eng\">
+                <com.izforge.izpack.panels.htmlhello.HTMLHelloPanel id=\"welcome\"/>
+                <com.izforge.izpack.panels.target.TargetPanel id=\"install_dir\">
+                    <installpath>$(pwd)/$VERAPDFPATH</installpath>
+                </com.izforge.izpack.panels.target.TargetPanel>
+                <com.izforge.izpack.panels.packs.PacksPanel id=\"sdk_pack_select\">
+                    <pack index=\"0\" name=\"veraPDF Mac and *nix Scripts\" selected=\"true\"/>
+                    <pack index=\"1\" name=\"veraPDF Validation model\" selected=\"true\"/>
+                    <pack index=\"2\" name=\"veraPDF Documentation\" selected=\"true\"/>
+                    <pack index=\"3\" name=\"veraPDF Sample Plugins\" selected=\"true\"/>
+                </com.izforge.izpack.panels.packs.PacksPanel>
+                <com.izforge.izpack.panels.install.InstallPanel id=\"install\"/>
+                <com.izforge.izpack.panels.finish.FinishPanel id=\"finish\"/>
+            </AutomatedInstallation>" > $VERAPDFPATH/install.xml
+          echo "Installing veraPDF"
+          VERAPDFINSTALLJAR=$(find $VERAPDFPATH -type f -name "*.jar" | head -n 1); [[ -z "$VERAPDFINSTALLJAR" ]] && { echo "No veraPDF installer found" >&2; exit 1; } || echo "veraPDF installer fount at $VERAPDFINSTALLJAR"
+          java -jar $VERAPDFINSTALLJAR $VERAPDFPATH/install.xml
+          echo "Creating test PDF (1)"
+          php -f examples/02_ZugferdDocumentPdfBuilder_EN16931.php
+          echo "Running PDF validation"
+          VERAPDFRESULT=$($VERAPDFPATH/verapdf --format text --flavour 3b --loglevel 0 examples/02_ZugferdDocumentPdfBuilder_PrintLayout_Merged.pdf)
+          echo "Result of validation"
+          echo $VERAPDFRESULT
+          [[ $VERAPDFRESULT == PASS* ]] && echo "PDF validation passed" || { echo "Error: PDF validation not passed" >&2; exit 1; }
+          echo "Creating test PDF (2)"
+          php -f examples/02_ZugferdDocumentPdfBuilder_XRECHNUNG.php
+          echo "Running PDF validation"
+          VERAPDFRESULT=$($VERAPDFPATH/verapdf --format text --flavour 3b --loglevel 0 examples/02_ZugferdDocumentPdfBuilder_PrintLayout_Merged.pdf)
+          echo "Result of validation"
+          echo $VERAPDFRESULT
+          [[ $VERAPDFRESULT == PASS* ]] && echo "PDF validation passed" || { echo "Error: PDF validation not passed" >&2; exit 1; }
 
       - name: Documentation
         continue-on-error: true
